# Generated by Django 5.1.4 on 2025-01-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='category',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Bank Account', 'Bank Account')], max_length=50),
        ),
        migrations.CreateModel(
            name='Fat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fat', to='tracker.wallet')),
            ],
        ),
    ]
